# Generated by Django 4.2.5 on 2023-10-03 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название урока')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тестовый', max_length=50, verbose_name='Название курса')),
                ('owner', models.CharField(max_length=50, verbose_name='Владелец')),
                ('lessons', models.ManyToManyField(to='stepik2.lesson')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Проудкты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, unique=True, verbose_name='Имитация данных пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UsersToProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepik2.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepik2.user')),
            ],
        ),
        migrations.CreateModel(
            name='UsersToLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_time', models.PositiveIntegerField(default=0, verbose_name='Время просмотра')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepik2.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepik2.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='lessons',
            field=models.ManyToManyField(through='stepik2.UsersToLessons', to='stepik2.lesson'),
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(through='stepik2.UsersToProducts', to='stepik2.product'),
        ),
    ]
